### ISSUE TITLE
Change stream name to be soft coded

### ISSUE THREAD

**Issue by alm4096** [alm865/FFMPEG-Live555-H264-H265-Streamer#2]

**Comment by lobnagenena** [comment]
hello, can you please tell me the command line for encoding a video file and stream it with live555?

**Comment by alm4096** [comment]
Maybe you should ask the makers of ffmpeg http://ffmpeg.org/ and live555 www.live555.com

This github is about coding your own program to do what you are asking and the command line options can be whatever you make them.

**Comment by lobnagenena** [comment]
Hello alm865,

I know how to test ffmpeg code and live555 separately but not together. I
thought of asking you since you are the one who posted the source code of
integrating both together. How can I test and run your code?

Best Regards,
Lobna Genena

**Comment by alm4096** [comment]
To test my code you simply need Microsoft Visual Studio and run the example code.

From your first question it sounds like you already have an encoded video file you want to stream in a certain format, my code example does not do that. My code takes already decoded video frames, such as frames from a Webcam, and encodes them into the video format of your choosing and streams them via rtsp.

Like i said before there is no "command line" in my example code, it's just a class for your C++ code. Typical usage would be if you have C++ code already grabbing some frames from a Webcam or file or you've generated them in code then want to encode and stream them via rtsp. I've done the encoding and streaming part for you, that is all.

To put out bluntly, you need to have a good understanding of C++ before you dive into my code. If you don't understand what a "class" is in a C++ environment then this code is going to be of little use to you.

Sorry but i don't think this code is what you are looking for since you're asking these questions.

If you are using Linux/Mac try piping the output from ffmpeg into live555. If you are on windows try using VLC with a batch file. Both will allow you to do what you are trying to do in the "command line". This is however completely off topic for what this code is intended to be used for.
