### ISSUE TITLE
get setup parameter from user 

### ISSUE THREAD

**Issue by ahmadi219** [alm865/FFMPEG-Live555-H264-H265-Streamer#5]
Hi 
I want to get parameter like input device name, width,  height and encoding type from user, So I create a form . 
in this project you use #define for encoding. How should I change code to set encoding type in run time ?

**Comment by alm4096** [comment]
That isn't quite that easy at the moment. I'm not 100% sure how to do it myself. The main issue is that way I have coded the Live555 thread. 

We are planning on removing the #defines in the future.

**Comment by alm4096** [comment]
Code has been updated to fix this issue.
Issue is now closed.
