### ISSUE TITLE
linux version of project

### ISSUE THREAD

**Issue by ahmadi219** [alm865/FFMPEG-Live555-H264-H265-Streamer#8]
Hi 
Is there a version of linux for this project ?
in this project you used HANDLE and some header files of windows kit. 
How can I build this project in linux platform ?
Thanks

**Comment by alm4096** [comment]
Yes it's possible but, there are no plans to port this example to Linux at this time. 

Live555 and ffmpeg have Linux examples, you could look them up and see how they have done it.
